name: Publish resume in JSONResume format as Github Page
on:
  push:
    branches: [ main ]

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v3
      - run:  mkdir dist
      - uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: rickosborne 
          resume_filepath: resume.json

          output_filepath: dist/index.html
          # modifies the index.html in-place
      - run:  ls -a 
      - run:  pwd
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #       name: github-pages
      #       path: /home/runner/work/Resume/Resume/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: /home/runner/work/Resume/Resume/dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

     
