name: Publish resume in JSONResume format as Github Page
on:
  push:
    branches: [ main ]

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v2
      - uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: macchiato
          resume_filepath: resume.json
          output_filepath: index.html
          # modifies the index.html in-place
      - run: ls -a 
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
            name: github-pages
            path: index.html
      - uses: actions/deploy-pages@v2
        name: Deploy to GitHub Pages
       

     
